site_name: Bucknet Org
site-url: https:Bucknet-org.github.io
site-author: Bucknet
site_description: A pioneer trustless reputation system for money markets

nav:
  - Introduction:
    - Intro: index.md
  - Consensus:
    - History: consensus/history.md
    - Architecture Overview: consensus/architecture_overview.md
    - Proof of Reputation: consensus/por.md
  
  - Architecture: 
    - Architecture: architecture/architecture.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - toc:
      title: On this page
      permalink: true